#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
bspc monitor DP-1 -d 9 10

bspc config border_width          3
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
#bspc config top_padding           0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^6' follow=off
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Blueberry.py state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Minecraft* 1.18.2 state=fullscreen

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

nitrogen --restore &
echo schedutil | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor &
bash ~/.screenlayout/monitors.sh &
pgrep -x polybar > /dev/null || polybar &
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x dunst > /dev/null || dunst &
sleep 2
rnnoise activate &
